apiVersion: v1
kind: ReplicationController
metadata:
  name: fast-api-deployment
  labels:
    app: fast-api
spec:
  replicas: 3
  selector:
    app: fast-api
  template:
    metadata:
      name: fast-api
      labels:
        app: fast-api
    spec:
      containers:
      - name: fast-api
        image: fast-api-image
        ports:
        - name: http-server
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
  labels:
    app:
      fast-api-service
spec:
  selector:
    app: fast-api
  ports:
  - port: 8000
    targetPort: 80
  type: LoadBalancer