name: terraform workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install kubeone
      run: curl -sfL get.kubeone.io | sh
    - name: install terraform    
      uses: hashicorp/setup-terraform@v1
    - name: Terraform initialization and plan
      run: |
        cd terraform
        terraform init
        terraform plan
