name: destroy terraform
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install terraform    
        uses: hashicorp/setup-terraform@v1
      
      - name: destroy terraform
        run: |
          cd terraform
          terraform destroy
