name: reset kubeone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install kubeone
        run: |
          curl -sfL get.kubeone.io | sh

      - name: reset kubeone
        run: |
          kubeone reset --manifest kubeone/kubeone.yaml -t terraform/tf.json
