name: nodes setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: install kubeone
        run: |
          curl -sfL get.kubeone.io | sh
      
      - name: see pods
        run: |
          kubectl --kubeconfig=github-actions-test-kubeconfig get nodes
          kubectl --kubeconfig=github-actions-test-kubeconfig get -n kube-system machinedeployment
          kubectl --kubeconfig=github-actions-test-kubeconfig apply -f nginx.deployment.yml
